Campaign screen and tasks setup for testing
mideind/Velthyding pull request #6
Opened 2021-03-26 15:08 UTC by vesteinn

2021-03-26 18:37 UTC, vthorsteinsson commented on src/features/campaigns/index.js
> +                                meta="Do translations convay meaning"
*convey

2021-03-26 18:37 UTC, vthorsteinsson commented on src/features/campaigns/index.js
> +                                description="Grade addequacy on a scale"
*adequacy

2021-04-15 12:18 UTC, peturorri commented on src/features/campaigntask/index.js
>      header: "Fluidity Task",
Heitir þetta ekki "fluency"?

2021-04-15 12:18 UTC, peturorri commented on src/features/campaigntask/index.js
> +                    <List.Item>5. All meaning</List.Item>
Ég held það mætti skilgreina þetta betur. Hver er munurinn á "much" og "most" og fleira í þeim dúr.

2021-04-15 12:18 UTC, peturorri commented on README.md
> +You’ll need to have Node >= 8.10 and npm >= 5.6 on your machine. You install dependancies run
"You install dependencies" -> "To install..."

2021-04-15 12:42 UTC, vesteinn commented on src/features/campaigntask/index.js
>      header: "Fluidity Task",
Jebb

2021-04-15 12:46 UTC, vesteinn commented on src/features/campaigntask/index.js
> +                    <List.Item>5. All meaning</List.Item>
Sammála því að það þurfi betri leiðbeiningar einhversstaðar, en þetta kemur héðan https://homepages.inf.ed.ac.uk/rsennric/mt18/5_4up.pdf

2021-04-15 12:50 UTC, peturorri commented on src/features/campaigntask/index.js
> +                    <List.Item>5. All meaning</List.Item>
Ok.

2021-04-19 14:50 UTC, HaukurPall requested changes

2021-04-19 14:50 UTC, HaukurPall commented on src/features/login/index.js
> +            <Header.Content>Login</Header.Content>
Ætti ekki að setja "Login" í localization?

2021-04-19 14:50 UTC, HaukurPall commented on src/features/campaigntask/index.js
> +      preference_id: props.targets[value][0],
Are these indices correct? Is `value` used correctly?

2021-04-19 14:50 UTC, HaukurPall commented on src/features/campaigntask/index.js
> +  const progress = Math.floor(100 * ((30 - tasksLeft) / 30));
`30` can be a constant like `maxStars` above.

2021-04-19 14:50 UTC, HaukurPall commented on src/features/campaigntask/index.js
> +    answerTask(id, answerData).then(() => updateTask());
You probably want to have some error handling here and decrement the tasks left in the positive case.

2021-04-19 14:50 UTC, HaukurPall commented on src/features/campaigntask/index.js
> +          sentence_b={task.targets[1][1]}
task.targets indices eru mjög ógagnsæ. Væri hægt að bæta inn athugasemd eða vísa í breytunöfn sem lýsa hvað þessar tölur standa fyrir?

2021-04-19 14:50 UTC, HaukurPall commented on src/features/campaigns/index.js
> +                  description="Is the output good and fluent"
Viljum við styðja þennan texta í i18n? Sama gildir um texta í `campaigntasks`.

2021-04-19 14:50 UTC, HaukurPall commented on src/features/campaigntask/index.js
> +      preference_id: props.targets[value][0],
Búið að laga þetta í nýrri útgáfu.

2021-04-21 14:38 UTC, vesteinn commented on src/features/campaigns/index.js
> +                  description="Is the output good and fluent"
Datt í hug að geyma þýðingar á þessum strengjum fyrir review svo það sé tryggt að það séu alltaf sömu leiðbeiningar, amk í bili

2021-04-23 09:41 UTC, HaukurPall approved these changes

2021-04-23 09:54 UTC, merged